import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "@/pages/Home.module.css";
import Link from "next/link";
import axios from "axios";
import type { ContactsType } from "@/pages/api/contacts";
import { useState } from "react";
import { z } from "zod";

const schema = z.object({
	id: z.string().min(10).max(16),
	title: z.string().min(3),
	name: z.string().min(3),
});

interface PropsType {
	contacts: ContactsType[];
}

export const getStaticProps: GetStaticProps = async () => {
	const { data } = await axios.get("http://localhost:3000/api/contacts", {
		headers: {
			"Application-Type": "application/json",
		},
	});

	return {
		props: {
			contacts: data,
		},
		revalidate: 10,
	};
};

const Home: NextPage<PropsType> = (props) => {
	const { contacts } = props;

	const [search, setSearch] = useState("");

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>

			<div>
				<input
					type="text"
					placeholder="type first name..."
					className={styles.search_bar}
					onChange={(e) => {
						setSearch(e.target.value);
					}}
				></input>
				<button>Search</button>
			</div>

			<nav>
				<Link href="/about">About</Link>
			</nav>

			<main>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
			</main>

			<div className={styles.table_holder}>
				<table className={styles.table}>
					<thead>
						<tr className={styles.table_head_holder}>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Email</th>
							<th>Phone</th>
						</tr>
					</thead>

					<tbody>
						{contacts
							?.filter((item) => {
								const term = search.toLowerCase();
								return term === ""
									? item
									: item.first_name.toLowerCase().includes(term);
							})
							.map((contact, index) => (
								<tr key={contact.id}>
									<td>{contact.first_name}</td>
									<td>{contact.last_name}</td>
									<td>{contact.email}</td>
									<td>{contact.phone}</td>
								</tr>
							))}
					</tbody>
				</table>
			</div>

			<p data-testid={`first-0`}>Hell: {contacts[0]?.first_name}</p>

			<footer>
				<p>Footer</p>
			</footer>
		</div>
	);
};

export default Home;
